package com.multicurrency.app.feature_currency_converter.shared.util

object DummyResponse {

     val currenciesSuccessResponse = """
        {
            "AED": "United Arab Emirates Dirham",
            "AFN": "Afghan Afghani",
            "ALL": "Albanian Lek",
            "AMD": "Armenian Dram",
            "ANG": "Netherlands Antillean Guilder",
            "AOA": "Angolan Kwanza",
            "ARS": "Argentine Peso",
            "AUD": "Australian Dollar",
            "AWG": "Aruban Florin",
            "AZN": "Azerbaijani Manat",
            "BAM": "Bosnia-Herzegovina Convertible Mark",
            "BBD": "Barbadian Dollar",
            "BDT": "Bangladeshi Taka",
            "BGN": "Bulgarian Lev",
            "BHD": "Bahraini Dinar",
            "BIF": "Burundian Franc",
            "BMD": "Bermudan Dollar",
            "BND": "Brunei Dollar",
            "BOB": "Bolivian Boliviano",
            "BRL": "Brazilian Real",
            "BSD": "Bahamian Dollar",
            "BTC": "Bitcoin",
            "BTN": "Bhutanese Ngultrum",
            "BWP": "Botswanan Pula",
            "BYN": "Belarusian Ruble",
            "BZD": "Belize Dollar",
            "CAD": "Canadian Dollar",
            "CDF": "Congolese Franc",
            "CHF": "Swiss Franc",
            "CLF": "Chilean Unit of Account (UF)",
            "CLP": "Chilean Peso",
            "CNH": "Chinese Yuan (Offshore)",
            "CNY": "Chinese Yuan",
            "COP": "Colombian Peso",
            "CRC": "Costa Rican Colón",
            "CUC": "Cuban Convertible Peso",
            "CUP": "Cuban Peso",
            "CVE": "Cape Verdean Escudo",
            "CZK": "Czech Republic Koruna",
            "DJF": "Djiboutian Franc",
            "DKK": "Danish Krone",
            "DOP": "Dominican Peso",
            "DZD": "Algerian Dinar",
            "EGP": "Egyptian Pound",
            "ERN": "Eritrean Nakfa",
            "ETB": "Ethiopian Birr",
            "EUR": "Euro",
            "FJD": "Fijian Dollar",
            "FKP": "Falkland Islands Pound",
            "GBP": "British Pound Sterling",
            "GEL": "Georgian Lari",
            "GGP": "Guernsey Pound",
            "GHS": "Ghanaian Cedi",
            "GIP": "Gibraltar Pound",
            "GMD": "Gambian Dalasi",
            "GNF": "Guinean Franc",
            "GTQ": "Guatemalan Quetzal",
            "GYD": "Guyanaese Dollar",
            "HKD": "Hong Kong Dollar",
            "HNL": "Honduran Lempira",
            "HRK": "Croatian Kuna",
            "HTG": "Haitian Gourde",
            "HUF": "Hungarian Forint",
            "IDR": "Indonesian Rupiah",
            "ILS": "Israeli New Sheqel",
            "IMP": "Manx pound",
            "INR": "Indian Rupee",
            "IQD": "Iraqi Dinar",
            "IRR": "Iranian Rial",
            "ISK": "Icelandic Króna",
            "JEP": "Jersey Pound",
            "JMD": "Jamaican Dollar",
            "JOD": "Jordanian Dinar",
            "JPY": "Japanese Yen",
            "KES": "Kenyan Shilling",
            "KGS": "Kyrgystani Som",
            "KHR": "Cambodian Riel",
            "KMF": "Comorian Franc",
            "KPW": "North Korean Won",
            "KRW": "South Korean Won",
            "KWD": "Kuwaiti Dinar",
            "KYD": "Cayman Islands Dollar",
            "KZT": "Kazakhstani Tenge",
            "LAK": "Laotian Kip",
            "LBP": "Lebanese Pound",
            "LKR": "Sri Lankan Rupee",
            "LRD": "Liberian Dollar",
            "LSL": "Lesotho Loti",
            "LYD": "Libyan Dinar",
            "MAD": "Moroccan Dirham",
            "MDL": "Moldovan Leu",
            "MGA": "Malagasy Ariary",
            "MKD": "Macedonian Denar",
            "MMK": "Myanma Kyat",
            "MNT": "Mongolian Tugrik",
            "MOP": "Macanese Pataca",
            "MRU": "Mauritanian Ouguiya",
            "MUR": "Mauritian Rupee",
            "MVR": "Maldivian Rufiyaa",
            "MWK": "Malawian Kwacha",
            "MXN": "Mexican Peso",
            "MYR": "Malaysian Ringgit",
            "MZN": "Mozambican Metical",
            "NAD": "Namibian Dollar",
            "NGN": "Nigerian Naira",
            "NIO": "Nicaraguan Córdoba",
            "NOK": "Norwegian Krone",
            "NPR": "Nepalese Rupee",
            "NZD": "New Zealand Dollar",
            "OMR": "Omani Rial",
            "PAB": "Panamanian Balboa",
            "PEN": "Peruvian Nuevo Sol",
            "PGK": "Papua New Guinean Kina",
            "PHP": "Philippine Peso",
            "PKR": "Pakistani Rupee",
            "PLN": "Polish Zloty",
            "PYG": "Paraguayan Guarani",
            "QAR": "Qatari Rial",
            "RON": "Romanian Leu",
            "RSD": "Serbian Dinar",
            "RUB": "Russian Ruble",
            "RWF": "Rwandan Franc",
            "SAR": "Saudi Riyal",
            "SBD": "Solomon Islands Dollar",
            "SCR": "Seychellois Rupee",
            "SDG": "Sudanese Pound",
            "SEK": "Swedish Krona",
            "SGD": "Singapore Dollar",
            "SHP": "Saint Helena Pound",
            "SLL": "Sierra Leonean Leone",
            "SOS": "Somali Shilling",
            "SRD": "Surinamese Dollar",
            "SSP": "South Sudanese Pound",
            "STD": "São Tomé and Príncipe Dobra (pre-2018)",
            "STN": "São Tomé and Príncipe Dobra",
            "SVC": "Salvadoran Colón",
            "SYP": "Syrian Pound",
            "SZL": "Swazi Lilangeni",
            "THB": "Thai Baht",
            "TJS": "Tajikistani Somoni",
            "TMT": "Turkmenistani Manat",
            "TND": "Tunisian Dinar",
            "TOP": "Tongan Pa'anga",
            "TRY": "Turkish Lira",
            "TTD": "Trinidad and Tobago Dollar",
            "TWD": "New Taiwan Dollar",
            "TZS": "Tanzanian Shilling",
            "UAH": "Ukrainian Hryvnia",
            "UGX": "Ugandan Shilling",
            "USD": "United States Dollar",
            "UYU": "Uruguayan Peso",
            "UZS": "Uzbekistan Som",
            "VEF": "Venezuelan Bolívar Fuerte (Old)",
            "VES": "Venezuelan Bolívar Soberano",
            "VND": "Vietnamese Dong",
            "VUV": "Vanuatu Vatu",
            "WST": "Samoan Tala",
            "XAF": "CFA Franc BEAC",
            "XAG": "Silver Ounce",
            "XAU": "Gold Ounce",
            "XCD": "East Caribbean Dollar",
            "XDR": "Special Drawing Rights",
            "XOF": "CFA Franc BCEAO",
            "XPD": "Palladium Ounce",
            "XPF": "CFP Franc",
            "XPT": "Platinum Ounce",
            "YER": "Yemeni Rial",
            "ZAR": "South African Rand",
            "ZMW": "Zambian Kwacha",
            "ZWL": "Zimbabwean Dollar"
        }
    """.trimIndent()

     val ratedSuccessResponse = """
    {
        "disclaimer": "Usage subject to terms: https://openexchangerates.org/terms",
        "license": "https://openexchangerates.org/license",
        "timestamp": 1705651200,
        "base": "USD",
        "rates": {
            "AED": 3.6729,
            "AFN": 73.023412,
            "ALL": 95.335652,
            "AMD": 404.653656,
            "ANG": 1.802816,
            "AOA": 830.592033,
            "ARS": 819.231756,
            "AUD": 1.519718,
            "AWG": 1.8025,
            "AZN": 1.7,
            "BAM": 1.796372,
            "BBD": 2,
            "BDT": 109.768074,
            "BGN": 1.79771,
            "BHD": 0.376958,
            "BIF": 2852.237753,
            "BMD": 1,
            "BND": 1.344075,
            "BOB": 6.911661,
            "BRL": 4.9298,
            "BSD": 1,
            "BTC": 0.000024252981,
            "BTN": 83.142889,
            "BWP": 13.656386,
            "BYN": 3.273546,
            "BZD": 2.016306,
            "CAD": 1.348714,
            "CDF": 2745.785871,
            "CHF": 0.868225,
            "CLF": 0.033345,
            "CLP": 920.09,
            "CNH": 7.20479,
            "CNY": 7.0995,
            "COP": 3967.999327,
            "CRC": 515.821631,
            "CUC": 1,
            "CUP": 25.75,
            "CVE": 101.291136,
            "CZK": 22.781775,
            "DJF": 178.104416,
            "DKK": 6.854305,
            "DOP": 58.857841,
            "DZD": 134.812086,
            "EGP": 30.9004,
            "ERN": 15,
            "ETB": 56.4,
            "EUR": 0.919163,
            "FJD": 2.2377,
            "FKP": 0.788267,
            "GBP": 0.788267,
            "GEL": 2.655,
            "GGP": 0.788267,
            "GHS": 12.003546,
            "GIP": 0.788267,
            "GMD": 67.275,
            "GNF": 8597.723383,
            "GTQ": 7.817488,
            "GYD": 209.435147,
            "HKD": 7.82049,
            "HNL": 24.710001,
            "HRK": 6.924385,
            "HTG": 131.651603,
            "HUF": 351.86988,
            "IDR": 15617.341321,
            "ILS": 3.748776,
            "IMP": 0.788267,
            "INR": 83.126157,
            "IQD": 1310.415571,
            "IRR": 42045,
            "ISK": 137.42,
            "JEP": 0.788267,
            "JMD": 155.202899,
            "JOD": 0.7094,
            "JPY": 148.27133333,
            "KES": 162,
            "KGS": 89.3021,
            "KHR": 4082.463603,
            "KMF": 453.000277,
            "KPW": 900,
            "KRW": 1336.27899,
            "KWD": 0.307787,
            "KYD": 0.833651,
            "KZT": 451.870828,
            "LAK": 20655,
            "LBP": 15062.5,
            "LKR": 321.303983,
            "LRD": 189.250025,
            "LSL": 18.91,
            "LYD": 4.82,
            "MAD": 9.968446,
            "MDL": 17.730764,
            "MGA": 4561,
            "MKD": 56.552517,
            "MMK": 2100.636873,
            "MNT": 3450,
            "MOP": 8.058754,
            "MRU": 39.55,
            "MUR": 44.260004,
            "MVR": 15.4,
            "MWK": 1683,
            "MXN": 17.171771,
            "MYR": 4.7195,
            "MZN": 63.850001,
            "NAD": 18.91,
            "NGN": 895.52,
            "NIO": 36.73,
            "NOK": 10.519873,
            "NPR": 133.034135,
            "NZD": 1.638301,
            "OMR": 0.384954,
            "PAB": 1,
            "PEN": 3.746406,
            "PGK": 3.740739,
            "PHP": 55.971494,
            "PKR": 280.1,
            "PLN": 4.030397,
            "PYG": 7291.152792,
            "QAR": 3.64085,
            "RON": 4.57369,
            "RSD": 107.739,
            "RUB": 88.809947,
            "RWF": 1273,
            "SAR": 3.750643,
            "SBD": 8.425461,
            "SCR": 13.408253,
            "SDG": 601,
            "SEK": 10.479075,
            "SGD": 1.342055,
            "SHP": 0.788267,
            "SLL": 20969.5,
            "SOS": 571.664591,
            "SRD": 36.95,
            "SSP": 130.26,
            "STD": 22281.8,
            "STN": 22.75,
            "SVC": 8.752647,
            "SYP": 2512.53,
            "SZL": 18.91,
            "THB": 35.5445,
            "TJS": 10.928131,
            "TMT": 3.5,
            "TND": 3.1115,
            "TOP": 2.366775,
            "TRY": 30.192286,
            "TTD": 6.792304,
            "TWD": 31.362499,
            "TZS": 2515,
            "UAH": 37.672177,
            "UGX": 3803.972549,
            "USD": 1,
            "UYU": 39.306864,
            "UZS": 12440,
            "VES": 36.001566,
            "VND": 24548.917039,
            "VUV": 118.722,
            "WST": 2.8,
            "XAF": 602.931404,
            "XAG": 0.04384715,
            "XAU": 0.00049308,
            "XCD": 2.70255,
            "XDR": 0.751461,
            "XOF": 602.931404,
            "XPD": 0.00105793,
            "XPF": 109.685322,
            "XPT": 0.0010948,
            "YER": 250.350066,
            "ZAR": 18.960299,
            "ZMW": 26.373011,
            "ZWL": 322
        }
    }
""".trimIndent()

    fun getResponseForEndpoint(endpoint: String): String {
        return when {
            endpoint.contains(CurrencyConverterConstants.Endpoints.FETCH_ALL_CURRENCIES) -> currenciesSuccessResponse
            endpoint.contains(CurrencyConverterConstants.Endpoints.FETCH_ALL_RATES) -> ratedSuccessResponse
            else -> ""
        }
    }

}